version: '3.8'
services:
  db:
    image: postgres:15
    container_name: nba_db
    environment:
      POSTGRES_USER: nba_user
      POSTGRES_PASSWORD: nba_password
      POSTGRES_DB: nba
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
volumes:
  db_data:
